[tool.poetry]
name = "Telegram Session Keeper"
version = "0.1.0"
description = "The library allows logging into a Telegram account and storing the session so that it can later be used to obtain a verification code for logging into the same account on another device."
authors = [ "Alex Deus" ]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
telethon = "^1.34.0"
click = "^8.3.1"
pydantic-settings = "^2.12.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
isort = "^5.13.2"
seed-isort-config = "^2.2.0"
black = "^23.12.1"
flake8 = "^7.0.0"
autoflake = "^2.2.1"
bandit = "^1.7.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_third_party = ["click", "pydantic_settings", "telethon"]
known_first_party = ["telegram_session_keeper"]

[tool.black]
line-length = 120
exclude = '''
/(
  \.git
  | tmp/
  | data/
)/
'''
